// AUTO-GENERATED by scripts/sync-prefabs.js. Do not edit by hand.
// Run `npm run sync-prefabs` after adding/removing files in /cheat-sheet-prefabs/.

export interface PrefabPack {
  /** Stable id, derived from the directory name. */
  slug: string
  /** Display name shown in the settings UI. */
  name: string
  /** Repo-relative paths under cheat-sheet-prefabs/. Combine with PREFAB_BASE_URL
   *  to fetch via raw.githubusercontent.com. */
  images: string[]
}

export const PREFAB_BASE_URL = 'https://raw.githubusercontent.com/scalpelpoe/scalpel/main/cheat-sheet-prefabs/'

export const PREFAB_PACKS: PrefabPack[] = [
  {
    slug: 'leagues',
    name: 'Leagues',
    images: [
      'leagues/Shipments.png',
      'leagues/Syndicate-328-2552.webp',
      'leagues/Syndicate-328.webp',
      'leagues/sanctum.png',
    ],
  },
]
