// AUTO-GENERATED by scripts/sync-prefabs.js. Do not edit by hand.
// Run `npm run sync-prefabs` after adding/removing files in /cheat-sheet-prefabs/.
//
// Image URLs are built at runtime by joining CHEAT_SHEET_PREFAB_BASE_URL (in
// shared/endpoints.ts) with each entry's relative `images` paths.

export interface PrefabPack {
  /** Stable id, derived from the directory name. */
  slug: string
  /** Display name shown in the settings UI. */
  name: string
  /** Repo-relative paths under cheat-sheet-prefabs/. */
  images: string[]
  /** When set, the pack only appears for users on the matching PoE version.
   *  Unset = visible in both. Configured via _poe.txt in the pack directory. */
  poeVersion?: 1 | 2
}

export const PREFAB_PACKS: PrefabPack[] = [
  {
    slug: 'leagues',
    name: 'Leagues',
    images: [
      'leagues/Shipments.png',
      'leagues/Syndicate-328-2552.webp',
      'leagues/Syndicate-328.webp',
      'leagues/sanctum.png',
    ],
    poeVersion: 1,
  },
]
