/**
 * Generate src/shared/data/cheat-sheet-prefabs.ts from the contents of
 * cheat-sheet-prefabs/. Each subdirectory becomes one starter pack; each
 * image inside it becomes one sheet in that pack. The runtime fetches each
 * image from its raw.githubusercontent.com URL when the user imports the
 * pack from the cheat-sheet settings tab.
 *
 *   cheat-sheet-prefabs/betrayal/aisling.png
 *      -> pack: { name: 'Betrayal', images: ['betrayal/aisling.png'] }
 *
 * Run manually: npm run sync-prefabs
 * The images directory is gitignored from the packaged build (electron-
 * builder only includes src/), so adding/removing prefab images doesn't
 * bloat the installer.
 */

const fs = require('fs')
const path = require('path')

const PREFAB_DIR = path.join(__dirname, '..', 'cheat-sheet-prefabs')
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'shared', 'data', 'cheat-sheet-prefabs.ts')

const ALLOWED_EXTS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp'])

/** Convert a directory name like 'path-of-building' to 'Path Of Building'.
 *  For overrides, drop a `_name.txt` file inside the pack directory containing
 *  the desired display name (e.g. 'Path of Building'). */
function packDisplayName(dir, slug) {
  const overridePath = path.join(dir, '_name.txt')
  if (fs.existsSync(overridePath)) return fs.readFileSync(overridePath, 'utf8').trim()
  return slug
    .split(/[-_]/g)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

/** Optional PoE version filter: drop a `_poe.txt` containing "1" or "2" in
 *  the pack directory to scope it to that game. No file = visible in both. */
function packPoeVersion(dir) {
  const overridePath = path.join(dir, '_poe.txt')
  if (!fs.existsSync(overridePath)) return undefined
  const raw = fs.readFileSync(overridePath, 'utf8').trim()
  if (raw === '1' || raw === '2') return Number(raw)
  return undefined
}

function main() {
  if (!fs.existsSync(PREFAB_DIR)) {
    console.error(`No prefab directory at ${PREFAB_DIR}`)
    process.exit(1)
  }

  const packs = []
  const slugs = fs
    .readdirSync(PREFAB_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()

  for (const slug of slugs) {
    const packDir = path.join(PREFAB_DIR, slug)
    const images = fs
      .readdirSync(packDir)
      .filter((f) => ALLOWED_EXTS.has(path.extname(f).toLowerCase()))
      .sort()
      .map((f) => `${slug}/${f}`)
    if (images.length === 0) continue
    const pack = { slug, name: packDisplayName(packDir, slug), images }
    const poeVersion = packPoeVersion(packDir)
    if (poeVersion) pack.poeVersion = poeVersion
    packs.push(pack)
  }

  const body = `// AUTO-GENERATED by scripts/sync-prefabs.js. Do not edit by hand.
// Run \`npm run sync-prefabs\` after adding/removing files in /cheat-sheet-prefabs/.
//
// Image URLs are built at runtime by joining CHEAT_SHEET_PREFAB_BASE_URL (in
// shared/endpoints.ts) with each entry's relative \`images\` paths.

export interface PrefabPack {
  /** Stable id, derived from the directory name. */
  slug: string
  /** Display name shown in the settings UI. */
  name: string
  /** Repo-relative paths under cheat-sheet-prefabs/. */
  images: string[]
  /** When set, the pack only appears for users on the matching PoE version.
   *  Unset = visible in both. Configured via _poe.txt in the pack directory. */
  poeVersion?: 1 | 2
}

export const PREFAB_PACKS: PrefabPack[] = ${JSON.stringify(packs, null, 2)}
`

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
  fs.writeFileSync(OUTPUT_FILE, body)
  const totalImages = packs.reduce((sum, p) => sum + p.images.length, 0)
  console.log(`Wrote ${packs.length} pack(s), ${totalImages} image(s) -> ${path.relative(process.cwd(), OUTPUT_FILE)}`)
}

main()
